---
name: test
bindings:
  sse0:
    type: sse-kafka
    kind: proxy
    routes:
      - exit: kafka0
        when:
          - path: /test
        with:
          topic: test
          filters:
            - key: example-key
              headers:
                zilla:identity: test
                tag: example-tag
