env:
  - name: KEYSTORE_PASSWORD
    value: generated

livenessProbePort: 7115
readinessProbePort: 7115

service:
  ports:
    - port: 7115
      name: http
    - port: 7144
      name: https

persistentVolumeClaims:
  zilla-web:
    mountPath: /var/www
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Mi
