args: ["start", "-v", "-e"]

extraEnv:
  - name: KEYSTORE_PASSWORD
    value: generated

livenessProbePort: 7183
readinessProbePort: 7183

service:
  ports:
    - port: 7183
      name: mqtt
    - port: 7883
      name: mqtts
