---
name: test
guards:
  test0:
    type: test
    options:
      roles:
        - write:items
bindings:
  http0:
    type: http-kafka
    kind: proxy
    routes:
      - guarded:
          test0:
            - write:items
        exit: kafka0
        when:
          - method: POST
            path: /items
        with:
          capability: produce
          topic: items-commands
          acks: leader_only
          key: ${idempotencyKey}
          overrides:
            zilla:identity: ${guarded['test0'].identity}
          reply-to: items-replies
