initContainers:
  - name: wait-for-zilla-config-server
    image: "busybox:1.36"
    command: ['/bin/sh', '-c', 'wget -S --spider http://zilla-config:7115/zilla.yaml']

extraEnv:
  - name: KEYSTORE_PASSWORD
    value: generated

args: ["start", "-v", "-e", "-p", "/etc/zilla/prop/zilla.properties"]

livenessProbePort: 7114
readinessProbePort: 7114

service:
  ports:
    - port: 7114
      name: http
    - port: 7143
      name: https

zilla.yaml: ""
