---
name: test
bindings:
    app0:
        type: http
        kind: client
        options:
            versions:
                - http/1.1
            overrides:
                :authority: localhost:8080
        exit: net0
