apiVersion: v1
kind: ConfigMap
metadata:
  name: zilla
data:
  zilla.yaml: |
{{ index .Values "zilla.yaml" | indent 4 }}

{{ range $name, $configMap := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
data:
{{- range $key, $value := $configMap.data }}
{{ $key | indent 2 }}: |
{{ $value  | indent 4 }}
{{- end }}
{{- end }}
