version: '3'
services:


  zilla:
    image: ghcr.io/aklivity/zilla:${ZILLA_VERSION}
    container_name: zilla
    pull_policy: always
    restart: unless-stopped
    ports:
      - 7114:7114
      - 7151:7151
      - 7183:7183
      - 7190:7190
    environment:
      KAFKA_BOOTSTRAP_SERVER: ${KAFKA_BOOTSTRAP_SERVER}
      ROUTE_GUIDE_SERVER_HOST: route-guide-server
      ROUTE_GUIDE_SERVER_PORT: 50051
    volumes:
      - ../../zilla.yaml:/etc/zilla/zilla.yaml
      - ./proto/:/etc/zilla/proto/
    command: start -v -e -Pzilla.engine.worker.capacity=512

  mqtt-simulator:
    image: ghcr.io/vordimous/mqtt-simulator:zilla-quickstart
    container_name: mqtt-simulator
    restart: unless-stopped
    volumes:
      - ./sim_settings.json:/usr/src/app/config/settings.json

  route-guide-server:
    image: ghcr.io/aklivity/extras-route-guide-server:sha-478b2ce
    container_name: route-guide-server
    restart: unless-stopped
    ports:
      - 50051:50051

networks:
  default:
    driver: bridge
