#
# Copyright 2021-2022 Aklivity Inc
#
# Licensed under the Aklivity Community License (the "License"); you may not use
# this file except in compliance with the License.  You may obtain a copy of the
# License at
#
#   https://www.aklivity.io/aklivity-community-license/
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OF ANY KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations under the License.
#

---
name: test
guards:
  test0:
    type: test
    options:
      roles:
        - service:echo
bindings:
  grpc0:
    type: grpc-kafka
    kind: proxy
    routes:
      - guarded:
          test0:
            - service:echo
        exit: kafka0
        when:
          - service: example.EchoService
            metadata:
              custom: test
        with:
          topic: requests
          acks: leader_only
          key: test
          overrides:
            zilla:identity: "${guarded['test0'].identity}"
          reply-to: responses
          filters:
            - key: "test"
              headers:
                zilla:identity: "${guarded['test0'].identity}"
